"""remove_unused_fields

Revision ID: e19aaab5ed5c
Revises: be5f21ea9bea
Create Date: 2026-05-03 22:17:37.183855

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e19aaab5ed5c"
down_revision: Union[str, Sequence[str], None] = "be5f21ea9bea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE payment_status_enum ADD VALUE 'processing' AFTER 'pending';")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("outbox_events", "attempts")
    op.drop_column("outbox_events", "next_retry_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "outbox_events",
        sa.Column(
            "next_retry_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "outbox_events",
        sa.Column(
            "attempts",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
